-- ============================================================
-- schema-pgvector.sql
-- CI-DB-017：PgVector 向量库扩展初始化（V2 AI Agent）
-- 关联：CR-20260801-004、docs/09-ai-agent-design.md §4.3、docs/08-pending-decisions.md D-013
-- ============================================================
-- 重要说明：
--   1. 此文件挂载到 **独立的 PostgreSQL (PgVector) 容器** 的 /docker-entrypoint-initdb.d/，
--      首次创建数据卷时由 PG 官方镜像自动执行；**不属于 MySQL 业务库**。
--   2. 本文件只负责启用 vector 扩展。向量表（ai_embedding）由 langchain4j
--      {@code PgVectorEmbeddingStore} 在应用首次连接时自动创建（createTable=true），
--      表结构以 langchain4j 标准（embedding_id/embedding/text/metadata）为准，避免方言冲突。
--   3. PgVector 只存"派生知识副本"，业务真源仍在 MySQL。边界约束见 docs/09 §2 B6。
--
-- 设计变更说明（2026-08-01，M8.0 实施时）：
--   原 schema-pgvector.sql 设计了 ai_knowledge_doc + ai_embedding(doc_id/model_name) 自定义结构，
--   M8.0 实施发现 langchain4j PgVectorEmbeddingStore 使用标准结构（embedding_id uuid / text / metadata jsonb），
--   两者不兼容。为避免双写冲突，统一由 langchain4j 管理向量表结构，本文件仅保留扩展创建。
--   原自定义结构的设计意图（派生知识、HNSW 索引）由 langchain4j 内置实现等价覆盖。
-- ============================================================

-- 启用向量扩展（pgvector 0.8.6，含 hnsw + ivfflat 访问方法）
CREATE EXTENSION IF NOT EXISTS vector;
